<?php
/**
 * Packaging
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Royal Mail API Shipping V3 (REST)
 *
 * API Shipping V3 (REST) provides the functionality for customers to take a shipping transaction from creation to collection.   It specifically covers how the Royal Mail API Shipping V3 can be used by business customers to conduct shipping activity with Royal Mail and provides the technical information to build this integration. This specification must be used with the relevant accompanying specifications for customers wishing to interface their systems with Royal Mail services.  Royal Mail API Shipping V3 exposes a fully RESTful service that allows account customers to create shipments, produce labels, and produce documentation for all the tasks required to ship domestic and international items with Royal Mail.  Built on industry standards, Royal Mail API Shipping V3 provides a simple and low cost method for customers to integrate with Royal Mail, and allows them to get shipping quickly. The API offers data streaming to allow customers greater flexibility when generating their labels. There are no costs to customers for using the Royal Mail API Shipping V3 services, however customers??? own development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.  This API can be used in conjunction with Royal Mail Pro Shipping, a GUI based shipping platform. For more details on Royal Mail Pro Shipping, including videos on and briefs on updating/ cancelling a shipment and Manifesting please refer to http://www.royalmail.com/pro-shipping-help.
 *
 * OpenAPI spec version: 3.0.20
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Packaging Class Doc Comment
 *
 * @category Class
 * @description Packaging details that are stored, to be used in shipment requests.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Packaging implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Packaging';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'packaging_id' => 'string',
        'name' => 'string',
        'weight' => 'double',
        'weight_unit_of_measure' => 'string',
        'length' => 'double',
        'width' => 'double',
        'height' => 'double'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'packaging_id' => null,
        'name' => null,
        'weight' => 'double',
        'weight_unit_of_measure' => null,
        'length' => 'double',
        'width' => 'double',
        'height' => 'double'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'packaging_id' => 'PackagingId',
        'name' => 'Name',
        'weight' => 'Weight',
        'weight_unit_of_measure' => 'WeightUnitOfMeasure',
        'length' => 'Length',
        'width' => 'Width',
        'height' => 'Height'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'packaging_id' => 'setPackagingId',
        'name' => 'setName',
        'weight' => 'setWeight',
        'weight_unit_of_measure' => 'setWeightUnitOfMeasure',
        'length' => 'setLength',
        'width' => 'setWidth',
        'height' => 'setHeight'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'packaging_id' => 'getPackagingId',
        'name' => 'getName',
        'weight' => 'getWeight',
        'weight_unit_of_measure' => 'getWeightUnitOfMeasure',
        'length' => 'getLength',
        'width' => 'getWidth',
        'height' => 'getHeight'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const WEIGHT_UNIT_OF_MEASURE_KG = 'KG';
    const WEIGHT_UNIT_OF_MEASURE_GRAMS = 'Grams';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getWeightUnitOfMeasureAllowableValues()
    {
        return [
            self::WEIGHT_UNIT_OF_MEASURE_KG,
            self::WEIGHT_UNIT_OF_MEASURE_GRAMS,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['packaging_id'] = isset($data['packaging_id']) ? $data['packaging_id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['weight'] = isset($data['weight']) ? $data['weight'] : null;
        $this->container['weight_unit_of_measure'] = isset($data['weight_unit_of_measure']) ? $data['weight_unit_of_measure'] : 'KG';
        $this->container['length'] = isset($data['length']) ? $data['length'] : null;
        $this->container['width'] = isset($data['width']) ? $data['width'] : null;
        $this->container['height'] = isset($data['height']) ? $data['height'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['packaging_id']) && (mb_strlen($this->container['packaging_id']) > 70)) {
            $invalidProperties[] = "invalid value for 'packaging_id', the character length must be smaller than or equal to 70.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 40)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 40.";
        }

        if (!is_null($this->container['weight']) && ($this->container['weight'] > 9999.999)) {
            $invalidProperties[] = "invalid value for 'weight', must be smaller than or equal to 9999.999.";
        }

        if (!is_null($this->container['weight']) && ($this->container['weight'] < 0.001)) {
            $invalidProperties[] = "invalid value for 'weight', must be bigger than or equal to 0.001.";
        }

        $allowedValues = $this->getWeightUnitOfMeasureAllowableValues();
        if (!is_null($this->container['weight_unit_of_measure']) && !in_array($this->container['weight_unit_of_measure'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'weight_unit_of_measure', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['length'] === null) {
            $invalidProperties[] = "'length' can't be null";
        }
        if (($this->container['length'] > 250)) {
            $invalidProperties[] = "invalid value for 'length', must be smaller than or equal to 250.";
        }

        if (($this->container['length'] < 0.01)) {
            $invalidProperties[] = "invalid value for 'length', must be bigger than or equal to 0.01.";
        }

        if ($this->container['width'] === null) {
            $invalidProperties[] = "'width' can't be null";
        }
        if (($this->container['width'] > 250)) {
            $invalidProperties[] = "invalid value for 'width', must be smaller than or equal to 250.";
        }

        if (($this->container['width'] < 0.01)) {
            $invalidProperties[] = "invalid value for 'width', must be bigger than or equal to 0.01.";
        }

        if ($this->container['height'] === null) {
            $invalidProperties[] = "'height' can't be null";
        }
        if (($this->container['height'] > 250)) {
            $invalidProperties[] = "invalid value for 'height', must be smaller than or equal to 250.";
        }

        if (($this->container['height'] < 0.01)) {
            $invalidProperties[] = "invalid value for 'height', must be bigger than or equal to 0.01.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets packaging_id
     *
     * @return string
     */
    public function getPackagingId()
    {
        return $this->container['packaging_id'];
    }

    /**
     * Sets packaging_id
     *
     * @param string $packaging_id Packaging Unique ID<br />Your unique identifier for these packaging details.<br />If not provided, a GUID will be generated.
     *
     * @return $this
     */
    public function setPackagingId($packaging_id)
    {
        if (!is_null($packaging_id) && (mb_strlen($packaging_id) > 70)) {
            throw new \InvalidArgumentException('invalid length for $packaging_id when calling Packaging., must be smaller than or equal to 70.');
        }

        $this->container['packaging_id'] = $packaging_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Name<br />The descriptive name of these packaging details
     *
     * @return $this
     */
    public function setName($name)
    {
        if ((mb_strlen($name) > 40)) {
            throw new \InvalidArgumentException('invalid length for $name when calling Packaging., must be smaller than or equal to 40.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets weight
     *
     * @return double
     */
    public function getWeight()
    {
        return $this->container['weight'];
    }

    /**
     * Sets weight
     *
     * @param double $weight Packaging Weight<br />The weight of this packaging.<br />Min weight: 1 gram.
     *
     * @return $this
     */
    public function setWeight($weight)
    {

        if (!is_null($weight) && ($weight > 9999.999)) {
            throw new \InvalidArgumentException('invalid value for $weight when calling Packaging., must be smaller than or equal to 9999.999.');
        }
        if (!is_null($weight) && ($weight < 0.001)) {
            throw new \InvalidArgumentException('invalid value for $weight when calling Packaging., must be bigger than or equal to 0.001.');
        }

        $this->container['weight'] = $weight;

        return $this;
    }

    /**
     * Gets weight_unit_of_measure
     *
     * @return string
     */
    public function getWeightUnitOfMeasure()
    {
        return $this->container['weight_unit_of_measure'];
    }

    /**
     * Sets weight_unit_of_measure
     *
     * @param string $weight_unit_of_measure Weight Unit of Measure
     *
     * @return $this
     */
    public function setWeightUnitOfMeasure($weight_unit_of_measure)
    {
        $allowedValues = $this->getWeightUnitOfMeasureAllowableValues();
        if (!is_null($weight_unit_of_measure) && !in_array($weight_unit_of_measure, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'weight_unit_of_measure', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['weight_unit_of_measure'] = $weight_unit_of_measure;

        return $this;
    }

    /**
     * Gets length
     *
     * @return double
     */
    public function getLength()
    {
        return $this->container['length'];
    }

    /**
     * Sets length
     *
     * @param double $length Packaging Length<br />The length of this packaging in CM
     *
     * @return $this
     */
    public function setLength($length)
    {

        if (($length > 250)) {
            throw new \InvalidArgumentException('invalid value for $length when calling Packaging., must be smaller than or equal to 250.');
        }
        if (($length < 0.01)) {
            throw new \InvalidArgumentException('invalid value for $length when calling Packaging., must be bigger than or equal to 0.01.');
        }

        $this->container['length'] = $length;

        return $this;
    }

    /**
     * Gets width
     *
     * @return double
     */
    public function getWidth()
    {
        return $this->container['width'];
    }

    /**
     * Sets width
     *
     * @param double $width Packaging Width<br />The width of this packaging in CM
     *
     * @return $this
     */
    public function setWidth($width)
    {

        if (($width > 250)) {
            throw new \InvalidArgumentException('invalid value for $width when calling Packaging., must be smaller than or equal to 250.');
        }
        if (($width < 0.01)) {
            throw new \InvalidArgumentException('invalid value for $width when calling Packaging., must be bigger than or equal to 0.01.');
        }

        $this->container['width'] = $width;

        return $this;
    }

    /**
     * Gets height
     *
     * @return double
     */
    public function getHeight()
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     *
     * @param double $height Packaging Height<br />The height of this packaging in CM
     *
     * @return $this
     */
    public function setHeight($height)
    {

        if (($height > 250)) {
            throw new \InvalidArgumentException('invalid value for $height when calling Packaging., must be smaller than or equal to 250.');
        }
        if (($height < 0.01)) {
            throw new \InvalidArgumentException('invalid value for $height when calling Packaging., must be bigger than or equal to 0.01.');
        }

        $this->container['height'] = $height;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset): mixed
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void 
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


