<?php
/**
 * PrintLabelResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Royal Mail API Shipping V3 (REST)
 *
 * API Shipping V3 (REST) provides the functionality for customers to take a shipping transaction from creation to collection.   It specifically covers how the Royal Mail API Shipping V3 can be used by business customers to conduct shipping activity with Royal Mail and provides the technical information to build this integration. This specification must be used with the relevant accompanying specifications for customers wishing to interface their systems with Royal Mail services.  Royal Mail API Shipping V3 exposes a fully RESTful service that allows account customers to create shipments, produce labels, and produce documentation for all the tasks required to ship domestic and international items with Royal Mail.  Built on industry standards, Royal Mail API Shipping V3 provides a simple and low cost method for customers to integrate with Royal Mail, and allows them to get shipping quickly. The API offers data streaming to allow customers greater flexibility when generating their labels. There are no costs to customers for using the Royal Mail API Shipping V3 services, however customers??? own development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.  This API can be used in conjunction with Royal Mail Pro Shipping, a GUI based shipping platform. For more details on Royal Mail Pro Shipping, including videos on and briefs on updating/ cancelling a shipment and Manifesting please refer to http://www.royalmail.com/pro-shipping-help.
 *
 * OpenAPI spec version: 3.0.20
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PrintLabelResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Response from a print label request, containing the label if the request was successful.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PrintLabelResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PrintLabelResponse"
     */
    public function testPrintLabelResponse()
    {
    }

    /**
     * Test attribute "shipment_id"
     */
    public function testPropertyShipmentId()
    {
    }

    /**
     * Test attribute "label_image"
     */
    public function testPropertyLabelImage()
    {
    }

    /**
     * Test attribute "label_image_format"
     */
    public function testPropertyLabelImageFormat()
    {
    }

    /**
     * Test attribute "tracking_number"
     */
    public function testPropertyTrackingNumber()
    {
    }

    /**
     * Test attribute "unique_id"
     */
    public function testPropertyUniqueId()
    {
    }

    /**
     * Test attribute "tracking_url"
     */
    public function testPropertyTrackingUrl()
    {
    }

    /**
     * Test attribute "carrier_code"
     */
    public function testPropertyCarrierCode()
    {
    }

    /**
     * Test attribute "primary2_d_barcode_image"
     */
    public function testPropertyPrimary2DBarcodeImage()
    {
    }

    /**
     * Test attribute "primary2_d_barcode_data"
     */
    public function testPropertyPrimary2DBarcodeData()
    {
    }

    /**
     * Test attribute "formatted_unique_id"
     */
    public function testPropertyFormattedUniqueId()
    {
    }

    /**
     * Test attribute "high_volume_barcode_data"
     */
    public function testPropertyHighVolumeBarcodeData()
    {
    }

    /**
     * Test attribute "high_volume_barcode_image"
     */
    public function testPropertyHighVolumeBarcodeImage()
    {
    }

    /**
     * Test attribute "high_volume_sort_code"
     */
    public function testPropertyHighVolumeSortCode()
    {
    }

    /**
     * Test attribute "primary1_d_barcode_data"
     */
    public function testPropertyPrimary1DBarcodeData()
    {
    }

    /**
     * Test attribute "primary1_d_barcode_image"
     */
    public function testPropertyPrimary1DBarcodeImage()
    {
    }

    /**
     * Test attribute "return_label_image_format"
     */
    public function testPropertyReturnLabelImageFormat()
    {
    }

    /**
     * Test attribute "return_label_image"
     */
    public function testPropertyReturnLabelImage()
    {
    }

    /**
     * Test attribute "routing"
     */
    public function testPropertyRouting()
    {
    }

    /**
     * Test attribute "http_status_code"
     */
    public function testPropertyHttpStatusCode()
    {
    }

    /**
     * Test attribute "http_status_description"
     */
    public function testPropertyHttpStatusDescription()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "errors"
     */
    public function testPropertyErrors()
    {
    }
}
